<?php include('includes/header.php') ?>

<section class=" main-hero-banner">

    <div class="blog-1 ">
        <div class="bannner-wrapper container">
            <h2 class="text-white">
            Career Development Programs
            </h2>
            <div>
                <nav style="--bs-breadcrumb-divider: '/';" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item text-white"><a href="http://localhost/kasthamandap/index.php#">Home</a></li>
                        <li class="breadcrumb-item text-white"><a href="http://localhost/kasthamandap/services.php">Services</a></li>
                        <li class="breadcrumb-item text-white"><a href="#">Career Development Programs</a></li>

                    </ol>
                </nav>
            </div>


            <div class="media-wrapper">
                <img src="./images/careerer.png" alt="">
            </div>

        </div>
    </div>



</section>
<section class=" trial py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-12">
                <div class="blog-content-card ">
                    <div class="blog-detail  p-5">
                        
                        <p>Making job decisions after moving to a new country may be both thrilling and quite difficult. 
                            A helpful hand is always welcome, and you will find just what you need in our career services. The main goal is to assist 
                            you in better understanding who you are and the visions and passions that will eventually help you launch a career. Additionally,
                             this will direct you in the direction of your desired career path,
                             putting you one step closer to getting the job of your dreams.</p>
                        <p>Kasthamandap Education sees you as a partner, and our main objective is to support you in achieving your goals. We begin
                             by evaluating your personality, interests, abilities, knowledge, and values before working with you
                             to choose the pathway that is most appropriate for you.</p>
                        <p>You will also receive grooming throughout this process to help you develop the abilities required to
                             land your desired career. Please do not hesitate to contact us if you are an international college graduate 
                             and have questions about your career. You will receive the best advice from our
                             counselors, and you will be "equipped to succeed in the real-time world."</p>
                         </div>

                </div>
            </div>
            <div class="col-md-4 col-sm-12">
                <div class="sticky">
                <div class="blog-content-card ">
                    <h3>More Content</h3>
                    <div class="content-card">
                        <img src="./images/education.png" alt="">
                        <div class="content-detail">
                            <h4>
                             <a href="http://localhost/kasthamandap/EDUCATION.PHP">Education</a>   </h4>
                            <p>At Kasthamandap Education, we take pride in our team of experts who wi...</p>
                        </div>
                    </div>

                    <div class="content-card">
                        <img src="./images/careerer.png" alt="">
                        <div class="content-detail">
                            <h4><a href="http://localhost/kasthamandap/CAREER.PHP">Career Development Programs</a></h4>
                            <p>Making job decisions after moving to a new country may be both thrilli...</p>
                        </div>
                    </div>

                    <div class="content-card">
                        <img src="./images/proffesinals.jpeg" alt="">
                        <div class="content-detail">
                            <h4><a href="http://localhost/kasthamandap/PROFESSION.PHP">Professional Year</a></h4>
                            <p>Professional Year Programs are the structured programs that focus on y...</p>
                        </div>
                    </div>
                </div>

                <div class="blog-country-card ">

                    <h3> Our Country</h3>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/CANADA.PHP">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>Canada</h6>
                        </a>
                    </div>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/AUSTRALIA.PHP">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>Australia</h6>
                        </a>
                    </div>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/NEWZEALAND.PHP">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>New Zealand</h6>
                        </a>
                    </div>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/UK.PHP">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>United Kingdom</h6>
                        </a>
                    </div>
                </div>

                <div class="blog-country-card ">
                    <h3> Our Courses</h3>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/PTE.php">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>PTE</h6>
                        </a>
                    </div>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/IELTS.php">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>IELTS</h6>
                        </a>
                    </div>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/TOFEL.php">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>TOFEL</h6>
                        </a>
                    </div>
                    
                </div>

                <div class="blog-country-card ">
                    <h3> Our Blogs</h3>
                   
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/internal-blog1.php">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>
                            5 ways to improve yourself</h6>
                        </a>
                    </div>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/internal-blog2.php">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>
                            Exploring Master's in Social Work Programs in Australia</h6>
                        </a>
                    </div>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/internal-blog3.php">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>Best Countries to study and work for Nepali students</h6>
                        </a>
                    </div>
                </div>

                </div>
            </div>
        </div>
    </div>
</section>
<?php include('includes/footer.php') ?>
