<?php include('includes/header.php') ?>

<section class=" main-hero-banner">

    <div class="blog-1 ">
        <div class="bannner-wrapper container">
            <h2 class="text-white">
            Education
            </h2>
            <div>
                <nav style="--bs-breadcrumb-divider: '/';" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item text-white"><a href="http://localhost/kasthamandap/index.php#">Home</a></li>
                        <li class="breadcrumb-item text-white"><a href="http://localhost/kasthamandap/services.php">Services</a></li>
                        <li class="breadcrumb-item text-white"><a href="#">Education</a></li>

                    </ol>
                </nav>
            </div>


            <div class="media-wrapper">
                <img src="./images/education.png" alt="">
            </div>

        </div>
    </div>



</section>
<section class=" trial py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-12">
                <div class="blog-content-card ">
                    <div class="blog-detail  p-5">
                        
                        <p>At Kasthamandap Education, we take pride in our team of experts who will guide you on your academic journey. For many years now, we have had an excellent track record of assisting young students with their college selections and admissions and the very fact that our academic counselors are QEAC certified with great experience will ensure you the best
                             of opportunities and an educational experience that is second to none.</p>
                        <p>Australia has definitely been a center of excellence and attraction for many International students. The land Down Under is one of the best destinations for students who want to learn, grow, and continuously strive for greatness. Choosing a University in a foreign land, full of exciting opportunities can however be an overwhelming process. This is where we come in, our experts are always available to 
                            help guide you throughout your journey and make the process more efficient.</p>
                        <p>At Kasthamandap Education, we believe that getting to know you better is the start of the process. That way, we can assess where you come from and personalize your needs and visions to make sure you get the right service that is the best for your endeavors. Next, we collaborate with the academic institution
                             of your choice to help process the application and secure your placement.</p>
                         </div>

                </div>
            </div>
            <div class="col-md-4 col-sm-12">
                <div class="sticky">
                <div class="blog-content-card ">
                    <h3>More Content</h3>
                    <div class="content-card">
                        <img src="./images/skills.jpeg" alt="">
                        <div class="content-detail">
                            <h4>
                             <a href="http://localhost/kasthamandap/EDUCATION.PHP">Skill Assessment</a>   </h4>
                            <p>Getting your skills assessed is one of the most vital components if yo...</p>
                        </div>
                    </div>

                    <div class="content-card">
                        <img src="./images/careerer.png" alt="">
                        <div class="content-detail">
                            <h4><a href="http://localhost/kasthamandap/CAREER.PHP">Career Development Programs</a></h4>
                            <p>Making job decisions after moving to a new country may be both thrilli...</p>
                        </div>
                    </div>

                    <div class="content-card">
                        <img src="./images/proffesinals.jpeg" alt="">
                        <div class="content-detail">
                            <h4><a href="http://localhost/kasthamandap/PROFESSION">Professional Year</a></h4>
                            <p>Professional Year Programs are the structured programs that focus on y...</p>
                        </div>
                    </div>
                </div>

                <div class="blog-country-card ">

                    <h3> Our Country</h3>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/CANADA.PHP">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>Canada</h6>
                        </a>
                    </div>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/AUSTRALIA.PHP">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>Australia</h6>
                        </a>
                    </div>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/NEWZEALAND.PHP">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>New Zealand</h6>
                        </a>
                    </div>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/UK.PHP">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>United Kingdom</h6>
                        </a>
                    </div>
                </div>

                <div class="blog-country-card ">
                    <h3> Our Courses</h3>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/PTE.php">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>PTE</h6>
                        </a>
                    </div>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/IELTS.php">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>IELTS</h6>
                        </a>
                    </div>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/TOFEL.php">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>TOFEL</h6>
                        </a>
                    </div>
                    
                </div>

                <div class="blog-country-card ">
                    <h3> Our Blogs</h3>
                   
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/internal-blog1.php">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>
                            5 ways to improve yourself</h6>
                        </a>
                    </div>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/internal-blog2.php">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>
                            Exploring Master's in Social Work Programs in Australia</h6>
                        </a>
                    </div>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/internal-blog3.php">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>Best Countries to study and work for Nepali students</h6>
                        </a>
                    </div>
                </div>

                </div>
            </div>
        </div>
    </div>
</section>
<?php include('includes/footer.php') ?>
