<?php include('includes/header.php') ?>

<section class=" main-hero-banner">

    <div class="blog-1 ">
        <div class="bannner-wrapper container">
            <h2 class="text-white">
            Professional Year
            </h2>
            <div>
                <nav style="--bs-breadcrumb-divider: '/';" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item text-white"><a href="http://localhost/kasthamandap/index.php#">Home</a></li>
                        <li class="breadcrumb-item text-white"><a href="http://localhost/kasthamandap/services.php">Services</a></li>
                        <li class="breadcrumb-item text-white"><a href="#">Professional Year</a></li>

                    </ol>
                </nav>
            </div>


            <div class="media-wrapper">
                <img src="./images/proffesinals.jpeg" alt="">
            </div>

        </div>
    </div>



</section>
<section class=" trial py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-12">
                <div class="blog-content-card ">
                    <div class="blog-detail  p-5">
                        
                        <p>Professional Year Programs are the structured programs that focus on your professional development by combining formal learning and workplace for international students. The program is designed for the recent graduates to help them bridge the gap between full-time study and professional employment. 
                            Furthermore, this will also help you secure your permanent residency in Australia.</p>
                        <p>These programs primarily focus on helping students develop industry-specific skills through both study and work experience. This ends up preparing students for their professional careers and gives them a better understanding of the culture and practices within the industry. Pictor Services has a huge connection and partnerships with the top PY Programs, so with our support, 
                            you will be sure to secure your professional career in Australia.</p>
                        <p><strong>Benefits of the Program?</strong></p>
                        <ul>
                            <li>Gain valuable experience in an Australian working environment through an internship placement.</li>
                            <li>Improve understanding of the culture and practices within the Australian workplace.</li>
                            <li>Refine your communication skills in a professional manner.</li>
                            <li>Completion of the program 
                                gives you five extra points on the Department of Immigration and Border</li>
                            <li>Protection when applying for a Skilled Independent visa.</li>
                            <li>Helps you build a network of professional like-minded individuals. Are you Eligible? a. It is necessary that you have graduated with a degree in Information Technology (IT), Accounting, Engineering (or a closely related subject) from Australia. b. You must be a holder of Skilled – Graduate (Temporary) Visa (Subclass 485) that allows
                                 you to be in Australia for 18 months after the completion of your education.</li>
                        </ul>
                         </div>

                </div>
            </div>
            <div class="col-md-4 col-sm-12">
                <div class="sticky">
                <div class="blog-content-card ">
                    <h3>More Content</h3>

                    <div class="content-card">
                        <img src="./images/skills.jpeg" alt="">
                        <div class="content-detail">
                            <h4>
                             <a href="http://localhost/kasthamandap/EDUCATION.PHP">Skill Assessment</a>   </h4>
                            <p>Getting your skills assessed is one of the most vital components if yo...</p>
                        </div>
                    </div>
                    <div class="content-card">
                        <img src="./images/education.png" alt="">
                        <div class="content-detail">
                            <h4>
                             <a href="http://localhost/kasthamandap/EDUCATION.PHP">Education</a>   </h4>
                            <p>At Kasthamandap Education, we take pride in our team of experts who wi...</p>
                        </div>
                    </div>

                    <div class="content-card">
                        <img src="./images/careerer.png" alt="">
                        <div class="content-detail">
                            <h4><a href="http://localhost/kasthamandap/CAREER.PHP">Career Development Programs</a></h4>
                            <p>Making job decisions after moving to a new country may be both thrilli...</p>
                        </div>
                    </div>

                    
                </div>

                <div class="blog-country-card ">

                    <h3> Our Country</h3>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/CANADA.PHP">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>Canada</h6>
                        </a>
                    </div>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/AUSTRALIA.PHP">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>Australia</h6>
                        </a>
                    </div>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/NEWZEALAND.PHP">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>New Zealand</h6>
                        </a>
                    </div>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/UK.PHP">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>United Kingdom</h6>
                        </a>
                    </div>
                </div>

                <div class="blog-country-card ">
                    <h3> Our Courses</h3>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/PTE.php">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>PTE</h6>
                        </a>
                    </div>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/IELTS.php">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>IELTS</h6>
                        </a>
                    </div>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/TOFEL.php">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>TOFEL</h6>
                        </a>
                    </div>
                    
                </div>

                <div class="blog-country-card ">
                    <h3> Our Blogs</h3>
                   
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/internal-blog1.php">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>
                            5 ways to improve yourself</h6>
                        </a>
                    </div>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/internal-blog2.php">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>
                            Exploring Master's in Social Work Programs in Australia</h6>
                        </a>
                    </div>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/internal-blog3.php">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>Best Countries to study and work for Nepali students</h6>
                        </a>
                    </div>
                </div>

                </div>
            </div>
        </div>
    </div>
</section>
<?php include('includes/footer.php') ?>
