<?php include('includes/header.php') ?>

<section class=" main-hero-banner">

    <div class="blog-1 ">
        <div class="bannner-wrapper container">
            <h2 class="text-white">
            Skill Assessment
            </h2>
            <div>
                <nav style="--bs-breadcrumb-divider: '/';" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item text-white"><a href="http://localhost/kasthamandap/index.php#">Home</a></li>
                        <li class="breadcrumb-item text-white"><a href="http://localhost/kasthamandap/services.php">Services</a></li>
                        <li class="breadcrumb-item text-white"><a href="#">Skill Assessment</a></li>

                    </ol>
                </nav>
            </div>


            <div class="media-wrapper">
                <img src="./images/skills.jpeg" alt="">
            </div>

        </div>
    </div>



</section>
<section class=" trial py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-12">
                <div class="blog-content-card ">
                    <div class="blog-detail  p-5">
                        
                        <p>Getting your skills assessed is one of the most vital components if you want to find yourself migrating to Australia on a permanent basis. Your skills will be put to a test with the specified standard and then evaluated to see
                             if the performance meets or exceeds the requirements.</p>
                        <p>These skills are generally assessed by relevant authorities that analyze if your skills meet/exceed the required standards set forth to work for a particular role in Australia. While most occupations have their own authority that assesses skills, it will be up to The Department of Home Affairs to accept a skill assessment which is issued by the relevant assessing authority. It is very necessary that you pass the assessment test to obtain certain visa subclasses. Needless to say, this process can be challenging, but we here at Pros Info Guild know our trade. With our
                             migration and career experts, you will find this process very simplified.</p>
                        <p>Our migration experts and agents will assist you throughout the process and submit all the necessary documents on your behalf to the relevant authorities. After passing the test, our team will work with you to prepare you for the technical interview and even assist you to land your dream job.</p>
                         </div>

                </div>
            </div>
            <div class="col-md-4 col-sm-12">
                <div class="sticky">
                <div class="blog-content-card ">
                    <h3>More Content</h3>
                    <div class="content-card">
                        <img src="./images/education.png" alt="">
                        <div class="content-detail">
                            <h4>
                             <a href="http://localhost/kasthamandap/EDUCATION.PHP">Education</a>   </h4>
                            <p>At Kasthamandap Education, we take pride in our team of experts who wi...</p>
                        </div>
                    </div>

                    <div class="content-card">
                        <img src="./images/careerer.png" alt="">
                        <div class="content-detail">
                            <h4><a href="http://localhost/kasthamandap/CAREER.PHP">Career Development Programs</a></h4>
                            <p>Making job decisions after moving to a new country may be both thrilli...</p>
                        </div>
                    </div>

                    <div class="content-card">
                        <img src="./images/proffesinals.jpeg" alt="">
                        <div class="content-detail">
                            <h4><a href="http://localhost/kasthamandap/PROFESSION.PHP">Professional Year</a></h4>
                            <p>Professional Year Programs are the structured programs that focus on y...</p>
                        </div>
                    </div>
                </div>

                <div class="blog-country-card ">

                    <h3> Our Country</h3>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/CANADA.PHP">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>Canada</h6>
                        </a>
                    </div>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/AUSTRALIA.PHP">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>Australia</h6>
                        </a>
                    </div>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/NEWZEALAND.PHP">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>New Zealand</h6>
                        </a>
                    </div>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/UK.PHP">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>United Kingdom</h6>
                        </a>
                    </div>
                </div>

                <div class="blog-country-card ">
                    <h3> Our Courses</h3>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/PTE.php">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>PTE</h6>
                        </a>
                    </div>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/IELTS.php">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>IELTS</h6>
                        </a>
                    </div>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/TOFEL.php">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>TOFEL</h6>
                        </a>
                    </div>
                    
                </div>

                <div class="blog-country-card ">
                    <h3> Our Blogs</h3>
                   
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/internal-blog1.php">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>
                            5 ways to improve yourself</h6>
                        </a>
                    </div>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/internal-blog2.php">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>
                            Exploring Master's in Social Work Programs in Australia</h6>
                        </a>
                    </div>
                    <div class="single-countries-list d-flex align-items-baseline gap-3 ">
                        <a class="single-countries-list d-flex align-items-baseline gap-3" href="http://localhost/kasthamandap/internal-blog3.php">
                            <i class="fa-solid fa-chevron-right"></i>
                            <h6>Best Countries to study and work for Nepali students</h6>
                        </a>
                    </div>
                </div>

                </div>
            </div>
        </div>
    </div>
</section>
<?php include('includes/footer.php') ?>
